apiVersion: v1
kind: Service
metadata:
  labels:
    app: backen-service
    sandbox: learn-kubernetes
    learn-kubernetes: backen-service
  name: backen-service
spec:
  ports:
  - name: 10000-tcp
    port: 10000
    protocol: TCP
    targetPort: 10000
  - name: 8443-tcp
    port: 8443
    protocol: TCP
    targetPort: 8443
  - name: 8778-tcp
    port: 8778
    protocol: TCP
    targetPort: 8778
  selector:
    app: backen-pod
  sessionAffinity: None
  type: ClusterIP