apiVersion: v1
kind: ConfigMap
metadata:
  name: backen-config
data:
  DB_SERVICE_NAME: db-service
  # DB: something heisst das es key/variable value hat und das value ist in diesem beispiel something