apiVersion: v1
kind: Service
metadata:
  name: db-service
  labels:
    sandbox: learn-kubernetes
    learn-kubernetes: db-service
spec:
  selector:
    app: db-pod
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306